language: php

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2

sudo: false

install:
  - composer update --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls --verbose
